import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import RecoilRootProvider from './component/RecoilRootProvider';
import DarkMode from './component/DarkMode';
import Header from './component/Header';
import Footer from './component/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'CatSAMA',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const darkMode = localStorage.getItem('darkMode') === 'true';
                if (darkMode) {
                  document.documentElement.classList.add('dark');
                } else {
                  document.documentElement.classList.remove('dark');
                }
              })();
            `,
          }}
        />
      </head>
      <body className={`${inter.className} dark:bg-gray-800`}>
        <RecoilRootProvider>
          <header>
            <Header />            
          </header>
          <main className="main-content">
            {children}
          </main>
          <footer>
            <Footer />
          </footer>
          <DarkMode />
        </RecoilRootProvider>
      </body>
    </html>
  );
}
